// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA5rAlgaKfMcnG1sYkCy3otzOhRUkWQRA',
    appId: '1:962476849560:web:7df05ebf4cafe1484893ed',
    messagingSenderId: '962476849560',
    projectId: 'auraeats-app',
    authDomain: 'auraeats-app.firebaseapp.com',
    storageBucket: 'auraeats-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVThty98nTtRdE2-Aafb7A2Teh3zpVElo',
    appId: '1:962476849560:android:03d128a6d7aaee1b4893ed',
    messagingSenderId: '962476849560',
    projectId: 'auraeats-app',
    storageBucket: 'auraeats-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDesgtP8lyINFlRM7bd7kmNXlg6G746GbU',
    appId: '1:962476849560:ios:a9cd052b04758f4f4893ed',
    messagingSenderId: '962476849560',
    projectId: 'auraeats-app',
    storageBucket: 'auraeats-app.firebasestorage.app',
    iosBundleId: 'com.example.auraeats',
  );
}
